---
- name: Check if Kubernetes has already been initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_conf

- name: Initialize Kubernetes Master
  command: kubeadm init --pod-network-cidr={{ pod_network_cidr }} --ignore-preflight-errors=NumCPU,Mem
  when: not kubeadm_conf.stat.exists

- name: Create .kube directory
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Install Calico Pod Network
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  become_user: "{{ ansible_user }}"
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  when: not kubeadm_conf.stat.exists

- name: Generate join command for workers
  command: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set join command as a fact
  set_fact:
    k8s_join_command: "{{ join_command_raw.stdout }}"