---
- name: Set dynamic worker hostname variable
  set_fact:
    new_hostname: "worker{{ groups['worker'].index(inventory_hostname) + 1 }}"

- name: Apply worker hostname to OS
  hostname:
    name: "{{ new_hostname }}"

- name: Update /etc/hosts with new worker hostname
  lineinfile:
    path: /etc/hosts
    line: "127.0.1.1 {{ new_hostname }}"
    state: present

- name: Check if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join the cluster
  command: "{{ hostvars[groups['master'][0]]['k8s_join_command'] }}"
  register: join_output
  failed_when: join_output.rc != 0
  when: not kubelet_conf.stat.exists

- name: Label worker node
  command: kubectl label node {{ new_hostname }} node-role.kubernetes.io/worker= --overwrite
  delegate_to: "{{ groups['master'][0] }}"
  become_user: "{{ hostvars[groups['master'][0]]['ansible_user'] }}"
  environment:
    KUBECONFIG: /home/{{ hostvars[groups['master'][0]]['ansible_user'] }}/.kube/config
  when: not kubelet_conf.stat.exists
